branch-defaults:
  aws-setup:
    environment: master-sweater-weather-wf
global:
  application_name: Sweater Weather API
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.4 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  profile: eb-cli
  repository: sweater-weather-wf
  sc: git
  workspace_type: Application
